name: Gradle Package

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: gradle :clean :build api:clean api:shadowJar spigot:clean spigot:build spigot:shadowJar

      - name: Upload build artifacts api
        uses: actions/upload-artifact@v1
        with:
          name: packetevents-api-2.0-build.jar
          path: api/build/libs

      - name: Upload build artifacts spigot
        uses: actions/upload-artifact@v1
        with:
          name: packetevents-spigot-2.0-build.jar
          path: spigot/build/libs

      - name: Upload build artifacts netty-common
        uses: actions/upload-artifact@v1
        with:
          name: packetevents-netty-common-2.0-build.jar
          path: netty-common/build/libs

      - name: Upload build artifacts bungeecord
        uses: actions/upload-artifact@v1
        with:
          name: packetevents-bungeecord-2.0-build.jar
          path: bungeecord/build/libs